[package]
name = "blackferrari2/sessiontrack"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@2.0.1"
t = "osyrisrblx/t@3.0.0"
Voyager = "blackferrari2/voyager@0.1.0"